---
- name: 既存のDocker関連パッケージを削除
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes
    autoremove: yes
  become: true
