---
- name: Linux開発環境の初期化
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: gitをインストールする
      apt:
        name: git
        state: present
        update_cache: yes

    - name: git user.name を設定
      become: false
      git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global

    - name: git user.email を設定
      become: false
      git_config:
        name: user.email
        value: "{{ git_user_email }}"
        scope: global

    - name: git core.autocrlf を設定
      become: false
      git_config:
        name: core.autocrlf
        value: "false"
        scope: global

    - name: git core.ignorecase を設定
      become: false
      git_config:
        name: core.ignorecase
        value: "false"
        scope: global

    - name: git core.quotepath を設定
      become: false
      git_config:
        name: core.quotepath
        value: "false"
        scope: global

    - name: git pull.rebase を設定
      become: false
      git_config:
        name: pull.rebase
        value: "false"
        scope: global

    - name: git color.ui を設定
      become: false
      git_config:
        name: color.ui
        value: "auto"
        scope: global

    - name: git core.editor を設定
      become: false
      git_config:
        name: core.editor
        value: "vi"
        scope: global
