- name: zshをインストールする
  apt:
    name: zsh
    state: present
    update_cache: yes

- name: oh-my-zshをインストールする
  become: false
  shell: |
    export HOME="{{ sudo_user_home }}"
    export RUNZSH=yes
    export KEEP_ZSHRC=no
    if [ -d "$HOME/.oh-my-zsh" ]; then
      yes | sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/uninstall.sh)"
    fi
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    chown -R {{ sudo_user }}:{{ sudo_user }} ~/.oh-my-zsh

- name: ユーザーのデフォルトシェルをzshに変更
  user:
    name: "{{ sudo_user }}"
    shell: /usr/bin/zsh
  become: true
