- name: zshをインストールする
  become: true
  become_user: "root"
  apt:
    name: zsh
    state: present
    update_cache: yes

- name: .oh-my-zshの存在確認
  ansible.builtin.stat:
    path: "$HOME/.oh-my-zsh"
  register: ohmyzsh_stat

- name: oh-my-zshをアンインストール（存在する場合）
  ansible.builtin.shell: |
    yes | sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/uninstall.sh)"
  when: ohmyzsh_stat.stat.exists

- name: zsh関連のゴミファイルを削除する
  ansible.builtin.shell: |
    rm -rf $HOME/.zshrc $HOME/.zsh_history $HOME/.zsh* $HOME/.oh-my-zsh
  ignore_errors: yes

- name: oh-my-zshをインストールする
  ansible.builtin.shell: |
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: .zshrcのテーマをcleanに変更する
  ansible.builtin.lineinfile:
    path: "$HOME/.zshrc"
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="clean"'
